spring.application.name=backend-sistema-clinico

# ========================================
# MySQL
# ========================================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/db-test-clinica}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:[PONER CONTRASEÑA AQUI]}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========================================
# JPA
# ========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format-sql=true

# ========================================
# JWT
# ========================================
jwt.secret=${JWT_SECRET:[PONER CLAVE SECRETA DE 256 BITS AQUI]}
jwt.access.expiration=900000
jwt.refresh.expiration=604800000

# ========================================
# Mercado Pago
# ========================================
mercadopago.access-token=${MP_ACCESS_TOKEN:[PONER ACCESS TOKEN DE MP AQUI]}

# ========================================
# App
# ========================================
app.precio-consulta=500
app.senia=1000
app.tiempo-liberacion-minutos=10
app.mp.notification-url=${MP_NOTIFICATION_URL:[PONER URL DE NGROK AQUI]/api/mercadopago/webhook}
app.mp.back-urls=${MP_BACK_URLS:http://localhost:5173}
