spring.application.name=backend-sistema-clinico

# ========================================
# MySQL
# ========================================
spring.datasource.url=jdbc:mysql://localhost:3306/db-test-clinica
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========================================
# JPA
# ========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format-sql=true

# ========================================
# JWT
# ========================================
jwt.secret=clinica_bot_jwt_secret_2024_super_seguro
jwt.access.expiration=900000
jwt.refresh.expiration=604800000

# ========================================
# Mercado Pago
# ========================================
mercadopago.access-token=APP_USR-4748013820148081-060517-44a190ca0100607ee7c62e3a14c53435-1257476049

# ========================================
# App
# ========================================
app.precio-consulta=500
app.senia=1000
app.tiempo-liberacion-minutos=10
app.mp.notification-url= https://topics-float-tackle-john.trycloudflare.com/api/mercadopago/webhook
app.mp.back-urls= https://topics-float-tackle-john.trycloudflare.com
app.n8n.webhook-confirmacion= https://pointed-nylon-few-aims.trycloudflare.com/webhook/confirmar-pago